import { Article } from '@/types/api'

export const mockArticles: Article[] = [
  {
    topics_id: 1,
    ymd: '2024-03-20',
    contents_type: 15,
    subject: 'AI技術の進歩が変える未来の働き方',
    title: 'AI技術の進歩が変える未来の働き方：2024年の最新トレンド',
    body: '<p>人工知能（AI）技術の急速な発展により、私たちの働き方は根本的な変革を迎えています。ChatGPTやGPT-4などの大規模言語モデルの登場により、従来の業務プロセスが大幅に効率化されています。</p><p>特に注目すべきは、創作活動やコンテンツ制作、データ分析といった分野での活用です。マーケティング業界では、AIがターゲット分析から広告文作成まで一貫してサポートし、従来の10倍の速度で成果を上げています。</p><p>しかし、AI導入には課題もあります。プライバシー保護、雇用への影響、倫理的な問題など、慎重に検討すべき点も多数存在します。今後は人間とAIの協働モデルが重要になるでしょう。</p>',
    plain_body: '人工知能（AI）技術の急速な発展により、私たちの働き方は根本的な変革を迎えています。ChatGPTやGPT-4などの大規模言語モデルの登場により、従来の業務プロセスが大幅に効率化されています。特に注目すべきは、創作活動やコンテンツ制作、データ分析といった分野での活用です。',
    topics_flg: 1,
    open_flg: 1,
    regular_flg: 0,
    inst_ymdhi: '2024-03-20T09:00:00+09:00',
    update_ymdhi: '2024-03-20T15:30:00+09:00',
    topics_group_id: 7,
    slug: 'ai-future-work-trends-2024',
    order_no: 1,
    favorite_cnt: 128,
    comment_cnt: 45,
    my_favorite_flg: false,
    group_nm: 'テクノロジーニュース',
    group_description: 'テクノロジー関連の最新情報',
    contents_type_cnt: 1,
    contents_type_nm: 'テクノロジー',
    contents_type_slug: 'technology',
    contents_type_parent_nm: null,
    category_parent_id: null,
    contents_type_ext_col_01: null,
    contents_type_ext_col_02: null,
    contents_type_ext_col_03: null,
    contents_type_ext_col_04: null,
    contents_type_ext_col_05: null,
    contents_type_list: [15],
    thumbnail: {
      id: '1_ext_01_0',
      url: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=400&fit=crop',
      url_org: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&h=630&fit=crop',
      desc: 'AI技術とビジネスの融合'
    },
    thumbnail_base64: '',
    theme: 'technology'
  },
  {
    topics_id: 2,
    ymd: '2024-03-19',
    contents_type: 16,
    subject: '持続可能な未来を築く環境技術の革新',
    title: '持続可能な未来を築く環境技術の革新：グリーンテックの最前線',
    body: '<p>地球温暖化対策が急務となる中、環境技術（グリーンテック）分野での革新的な取り組みが注目を集めています。太陽光発電の効率向上、風力発電の大型化、そして蓄電池技術の飛躍的な進歩により、再生可能エネルギーのコストは従来の化石燃料を下回るまでになりました。</p><p>特に期待されているのは、カーボンキャプチャー技術です。空気中のCO2を直接回収し、有用な化学物質に変換する技術が実用化段階に入っています。この技術により、温室効果ガスの削減と新たな産業の創出を同時に実現できる可能性があります。</p><p>日本企業も積極的に参入しており、トヨタの水素燃料電池車、パナソニックの高効率太陽電池、村田製作所の次世代蓄電池など、世界をリードする技術を次々と発表しています。</p>',
    plain_body: '地球温暖化対策が急務となる中、環境技術（グリーンテック）分野での革新的な取り組みが注目を集めています。太陽光発電の効率向上、風力発電の大型化、そして蓄電池技術の飛躍的な進歩により、再生可能エネルギーのコストは従来の化石燃料を下回るまでになりました。',
    topics_flg: 1,
    open_flg: 1,
    regular_flg: 0,
    inst_ymdhi: '2024-03-19T14:30:00+09:00',
    update_ymdhi: '2024-03-19T16:45:00+09:00',
    topics_group_id: 8,
    slug: 'green-tech-innovation-2024',
    order_no: 2,
    favorite_cnt: 89,
    comment_cnt: 23,
    my_favorite_flg: false,
    group_nm: '環境・エネルギー',
    group_description: '環境とエネルギー関連のニュース',
    contents_type_cnt: 1,
    contents_type_nm: '環境',
    contents_type_slug: 'environment',
    contents_type_parent_nm: null,
    category_parent_id: null,
    contents_type_ext_col_01: null,
    contents_type_ext_col_02: null,
    contents_type_ext_col_03: null,
    contents_type_ext_col_04: null,
    contents_type_ext_col_05: null,
    contents_type_list: [16],
    thumbnail: {
      id: '2_ext_01_0',
      url: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&h=400&fit=crop',
      url_org: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=1200&h=630&fit=crop',
      desc: '再生可能エネルギーの風車'
    },
    thumbnail_base64: '',
    theme: 'environment'
  },
  {
    topics_id: 3,
    ymd: '2024-03-18',
    contents_type: 17,
    subject: 'Web3とブロックチェーンが創る新しいインターネット',
    title: 'Web3とブロックチェーンが創る新しいインターネット：分散型社会の到来',
    body: '<p>Web3技術の普及により、インターネットの概念が根本的に変わろうとしています。従来の中央集権型プラットフォームから、ユーザーが自らのデータと資産をコントロールできる分散型システムへの移行が進んでいます。</p><p>ブロックチェーン技術を基盤とするDeFi（分散型金融）は、銀行を介さずに金融取引を可能にし、世界中で数兆円規模の市場を形成しています。また、NFT（非代替トークン）によりデジタルアートや音楽の新しい所有権概念が生まれ、クリエイターエコノミーが活性化しています。</p><p>企業も積極的に参入しており、メタバース空間でのビジネス展開、スマートコントラクトによる自動化システム、DAOによる新しい組織運営形態など、革新的な取り組みが続々と登場しています。</p>',
    plain_body: 'Web3技術の普及により、インターネットの概念が根本的に変わろうとしています。従来の中央集権型プラットフォームから、ユーザーが自らのデータと資産をコントロールできる分散型システムへの移行が進んでいます。',
    topics_flg: 1,
    open_flg: 1,
    regular_flg: 0,
    inst_ymdhi: '2024-03-18T11:15:00+09:00',
    update_ymdhi: '2024-03-18T13:20:00+09:00',
    topics_group_id: 7,
    slug: 'web3-blockchain-decentralized-internet',
    order_no: 3,
    favorite_cnt: 156,
    comment_cnt: 67,
    my_favorite_flg: false,
    group_nm: 'テクノロジーニュース',
    group_description: 'テクノロジー関連の最新情報',
    contents_type_cnt: 1,
    contents_type_nm: 'ブロックチェーン',
    contents_type_slug: 'blockchain',
    contents_type_parent_nm: null,
    category_parent_id: null,
    contents_type_ext_col_01: null,
    contents_type_ext_col_02: null,
    contents_type_ext_col_03: null,
    contents_type_ext_col_04: null,
    contents_type_ext_col_05: null,
    contents_type_list: [17],
    thumbnail: {
      id: '3_ext_01_0',
      url: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=400&fit=crop',
      url_org: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200&h=630&fit=crop',
      desc: 'ブロックチェーンネットワークの可視化'
    },
    thumbnail_base64: '',
    theme: 'blockchain'
  },
  {
    topics_id: 4,
    ymd: '2024-03-17',
    contents_type: 18,
    subject: '量子コンピュータが切り開く計算の新時代',
    title: '量子コンピュータが切り開く計算の新時代：量子優位性の実現',
    body: '<p>量子コンピュータ技術の進歩により、従来のコンピュータでは解決困難だった問題の解決が現実味を帯びています。IBM、Google、Amazon、そして日本のRiken（理化学研究所）など、世界の主要機関が量子コンピュータの実用化に向けて激しい開発競争を繰り広げています。</p><p>特に注目されているのは、薬物開発における分子シミュレーション、金融業界でのポートフォリオ最適化、暗号解読、気象予測の精度向上などの分野です。これらの領域では、量子コンピュータの並列計算能力により、計算時間を数日から数分へと劇的に短縮できる可能性があります。</p><p>一方で、量子コンピュータの実用化には技術的課題も多く、量子エラー修正、量子もつれの維持、極低温環境の維持など、解決すべき問題は山積しています。</p>',
    plain_body: '量子コンピュータ技術の進歩により、従来のコンピュータでは解決困難だった問題の解決が現実味を帯びています。IBM、Google、Amazon、そして日本のRiken（理化学研究所）など、世界の主要機関が量子コンピュータの実用化に向けて激しい開発競争を繰り広げています。',
    topics_flg: 1,
    open_flg: 1,
    regular_flg: 0,
    inst_ymdhi: '2024-03-17T08:45:00+09:00',
    update_ymdhi: '2024-03-17T10:15:00+09:00',
    topics_group_id: 7,
    slug: 'quantum-computing-new-era',
    order_no: 4,
    favorite_cnt: 203,
    comment_cnt: 89,
    my_favorite_flg: false,
    group_nm: 'テクノロジーニュース',
    group_description: 'テクノロジー関連の最新情報',
    contents_type_cnt: 1,
    contents_type_nm: '量子技術',
    contents_type_slug: 'quantum',
    contents_type_parent_nm: null,
    category_parent_id: null,
    contents_type_ext_col_01: null,
    contents_type_ext_col_02: null,
    contents_type_ext_col_03: null,
    contents_type_ext_col_04: null,
    contents_type_ext_col_05: null,
    contents_type_list: [18],
    thumbnail: {
      id: '4_ext_01_0',
      url: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&h=400&fit=crop',
      url_org: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=1200&h=630&fit=crop',
      desc: '量子コンピュータの内部構造'
    },
    thumbnail_base64: '',
    theme: 'quantum'
  },
  {
    topics_id: 5,
    ymd: '2024-03-16',
    contents_type: 19,
    subject: 'スマートシティで実現する持続可能な都市生活',
    title: 'スマートシティで実現する持続可能な都市生活：IoTが変える街づくり',
    body: '<p>IoT（Internet of Things）技術の普及により、都市インフラの効率化と住民の生活品質向上を同時に実現するスマートシティプロジェクトが世界各地で進行しています。センサーネットワーク、AI分析、ビッグデータ活用により、交通渋滞の解消、エネルギー効率の最適化、公共サービスの向上が実現されています。</p><p>シンガポールの「Smart Nation」プロジェクトでは、全市域にセンサーを配置し、リアルタイムでの都市管理を実現。交通量に応じた信号制御、気象データに基づく街路樹の水やり、人流データを活用した公共交通の最適化など、市民生活の質を大幅に向上させています。</p><p>日本でも、東京都の「デジタルツイン」プロジェクト、大阪・関西万博での次世代都市モデル実証など、革新的な取り組みが始まっています。これらの技術により、都市の持続可能性と住民の利便性を両立する新しい街づくりが実現しつつあります。</p>',
    plain_body: 'IoT（Internet of Things）技術の普及により、都市インフラの効率化と住民の生活品質向上を同時に実現するスマートシティプロジェクトが世界各地で進行しています。センサーネットワーク、AI分析、ビッグデータ活用により、交通渋滞の解消、エネルギー効率の最適化、公共サービスの向上が実現されています。',
    topics_flg: 1,
    open_flg: 1,
    regular_flg: 0,
    inst_ymdhi: '2024-03-16T16:20:00+09:00',
    update_ymdhi: '2024-03-16T18:30:00+09:00',
    topics_group_id: 9,
    slug: 'smart-city-sustainable-urban-life',
    order_no: 5,
    favorite_cnt: 134,
    comment_cnt: 56,
    my_favorite_flg: false,
    group_nm: '都市・社会',
    group_description: '都市開発と社会システム関連のニュース',
    contents_type_cnt: 1,
    contents_type_nm: 'スマートシティ',
    contents_type_slug: 'smart-city',
    contents_type_parent_nm: null,
    category_parent_id: null,
    contents_type_ext_col_01: null,
    contents_type_ext_col_02: null,
    contents_type_ext_col_03: null,
    contents_type_ext_col_04: null,
    contents_type_ext_col_05: null,
    contents_type_list: [19],
    thumbnail: {
      id: '5_ext_01_0',
      url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&h=400&fit=crop',
      url_org: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1200&h=630&fit=crop',
      desc: '近未来的なスマートシティの夜景'
    },
    thumbnail_base64: '',
    theme: 'smart-city'
  },
  {
    topics_id: 6,
    ymd: '2024-03-21',
    contents_type: 15,
    subject: '最新記事：生成AIがコンテンツ制作業界に革命をもたらす',
    title: '生成AIがコンテンツ制作業界に革命をもたらす：クリエイターの新時代',
    body: '<p>【最新】生成AI技術の進歩により、コンテンツ制作業界が大きな変革期を迎えています。テキスト生成、画像生成、動画編集、音楽作曲まで、AIがクリエイティブワークの様々な分野でアシスタント役を担うようになりました。</p><p>Adobe、Canva、Figmaなどのデザインツールでは、AI機能が標準搭載され、デザイナーの作業効率が大幅に向上しています。また、動画制作では、AIが自動で字幕生成、カット編集、エフェクト適用を行い、従来数日かかっていた作業を数時間で完了できるようになりました。</p><p>一方で、AIと人間の創造性のバランス、著作権の問題、オリジナリティの維持など、新たな課題も浮上しています。今後はAIを活用しながらも、人間ならではの感性と創造力を大切にしたコンテンツ制作が求められるでしょう。</p>',
    plain_body: '生成AI技術の進歩により、コンテンツ制作業界が大きな変革期を迎えています。テキスト生成、画像生成、動画編集、音楽作曲まで、AIがクリエイティブワークの様々な分野でアシスタント役を担うようになりました。',
    topics_flg: 1,
    open_flg: 1,
    regular_flg: 0,
    inst_ymdhi: '2024-03-21T10:30:00+09:00',
    update_ymdhi: '2024-03-21T12:45:00+09:00',
    topics_group_id: 7,
    slug: 'generative-ai-content-creation-revolution',
    order_no: 6,
    favorite_cnt: 87,
    comment_cnt: 34,
    my_favorite_flg: false,
    group_nm: 'テクノロジーニュース',
    group_description: 'テクノロジー関連の最新情報',
    contents_type_cnt: 1,
    contents_type_nm: 'AI・機械学習',
    contents_type_slug: 'ai-ml',
    contents_type_parent_nm: null,
    category_parent_id: null,
    contents_type_ext_col_01: null,
    contents_type_ext_col_02: null,
    contents_type_ext_col_03: null,
    contents_type_ext_col_04: null,
    contents_type_ext_col_05: null,
    contents_type_list: [15],
    thumbnail: {
      id: '6_ext_01_0',
      url: 'https://images.unsplash.com/photo-1677756119517-756a188d2d94?w=800&h=400&fit=crop',
      url_org: 'https://images.unsplash.com/photo-1677756119517-756a188d2d94?w=1200&h=630&fit=crop',
      desc: 'AI生成アートとクリエイティビティ'
    },
    thumbnail_base64: '',
    theme: 'ai-creativity'
  }
]

// ビルド時に使用する主要記事（SSG用）
export const featuredArticles = mockArticles.slice(0, 5)

// 最新記事を日時順で取得する関数
export const getLatestArticles = (count: number = 5): Article[] => {
  return [...mockArticles]
    .sort((a, b) => new Date(b.inst_ymdhi).getTime() - new Date(a.inst_ymdhi).getTime())
    .slice(0, count)
}